// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqv0IIZZILDWyoDsGmQQ7evP39fo2pyY',
    appId: '1:692291790866:web:e9c7f084796633e24410cb',
    messagingSenderId: '692291790866',
    projectId: 'moneypal-69',
    authDomain: 'moneypal-69.firebaseapp.com',
    storageBucket: 'moneypal-69.firebasestorage.app',
    measurementId: 'G-H44K4QZ0CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD20cKlb23FTtpSbgXdUOEJcL7psagawpE',
    appId: '1:692291790866:android:3f0ffce56a0eaffc4410cb',
    messagingSenderId: '692291790866',
    projectId: 'moneypal-69',
    storageBucket: 'moneypal-69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC5UEzreD51rPLLkMtekk1ei-VxOh0J3w',
    appId: '1:692291790866:ios:716f461d012ace7f4410cb',
    messagingSenderId: '692291790866',
    projectId: 'moneypal-69',
    storageBucket: 'moneypal-69.firebasestorage.app',
    iosBundleId: 'urva.moneypal.com.moneypalFolder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC5UEzreD51rPLLkMtekk1ei-VxOh0J3w',
    appId: '1:692291790866:ios:716f461d012ace7f4410cb',
    messagingSenderId: '692291790866',
    projectId: 'moneypal-69',
    storageBucket: 'moneypal-69.firebasestorage.app',
    iosBundleId: 'urva.moneypal.com.moneypalFolder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvqv0IIZZILDWyoDsGmQQ7evP39fo2pyY',
    appId: '1:692291790866:web:c7fe4a1dd8c91a954410cb',
    messagingSenderId: '692291790866',
    projectId: 'moneypal-69',
    authDomain: 'moneypal-69.firebaseapp.com',
    storageBucket: 'moneypal-69.firebasestorage.app',
    measurementId: 'G-PMB999BJ0V',
  );
}
